// <auto-generated />
using System;
using ContactMgrApp.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ContactMgrApp.Migrations
{
    [DbContext(typeof(ContactContext))]
    partial class ContactContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ContactMgrApp.Models.Category", b =>
                {
                    b.Property<int>("CategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryID");

                    b.ToTable("Cateories");

                    b.HasData(
                        new
                        {
                            CategoryID = 1,
                            Name = "Family"
                        },
                        new
                        {
                            CategoryID = 2,
                            Name = "Friend"
                        },
                        new
                        {
                            CategoryID = 3,
                            Name = "Work"
                        },
                        new
                        {
                            CategoryID = 4,
                            Name = "Other"
                        });
                });

            modelBuilder.Entity("ContactMgrApp.Models.Contact", b =>
                {
                    b.Property<int>("ContactID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CategoryID")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Orginazation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ContactID");

                    b.HasIndex("CategoryID");

                    b.ToTable("Contacts");

                    b.HasData(
                        new
                        {
                            ContactID = 1,
                            CategoryID = 1,
                            DateAdded = new DateTime(2020, 2, 12, 19, 16, 6, 420, DateTimeKind.Local).AddTicks(5640),
                            Email = "marryellen@yahoo.com",
                            FirstName = "Marry Ellen",
                            LastName = "Walton",
                            Phone = "555-123-1234"
                        },
                        new
                        {
                            ContactID = 2,
                            CategoryID = 2,
                            DateAdded = new DateTime(2020, 2, 12, 19, 16, 6, 425, DateTimeKind.Local).AddTicks(5650),
                            Email = "delores@yahoo.com",
                            FirstName = "Delores",
                            LastName = "Del Rio",
                            Phone = "555-987-6543"
                        },
                        new
                        {
                            ContactID = 3,
                            CategoryID = 3,
                            DateAdded = new DateTime(2020, 2, 12, 19, 16, 6, 425, DateTimeKind.Local).AddTicks(5690),
                            Email = "efren@yahoo.com",
                            FirstName = "Efren",
                            LastName = "Herrera",
                            Phone = "555-111-1111"
                        });
                });

            modelBuilder.Entity("ContactMgrApp.Models.Contact", b =>
                {
                    b.HasOne("ContactMgrApp.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
