using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace ContactMgrApp.Models
{
	public class Contact
	{
		//primary key - generated by database
		[Key]
		public int ContactID { get; set; }

		[Required(ErrorMessage = "Please enter a first name")]
		public string FirstName { get; set; }

		[Required(ErrorMessage = "Please enter a last name")]
		public string LastName { get; set; }

		[Required(ErrorMessage = "Please enter a phone number")]
		public string Phone { get; set; }

		[Required(ErrorMessage = "Please enter an email")]
		public string Email { get; set; }

		public string Orginazation { get; set; } //No validation - optional

		public DateTime DateAdded { get; set; } //Will be set by app

		//Foreign Key
		[ForeignKey("CategoryID")]
		public Category Category { get; set; }

		[Range(1, 100000000, ErrorMessage = "Please Select a category")]
		public int CategoryID { get; set; }

		//Read only property
		public string Slug => FirstName?.Replace(' ', '-').ToLower()
			+ '-' + LastName?.Replace(' ', '-').ToLower();
	}
}
